### ISSUE TITLE
Data Table doesn't show up in Dashboard

### ISSUE THREAD

**Issue by andrewpbray** [gradebook-dev/gradebook-app#102]
**Describe the bug**
When I added the Lab assignments to the Lab category in the Stat 20 policy file, it gave an error message and did not show the data table.

**To Reproduce**
1. See `stat20-in-app-II.mov` in slack

**Expected behavior**
Data Table is *always* viewable, even when you don't have any category grades yet.

**Comment by andrewpbray** [comment]
Note that on running the app, the following message appears:

<img width="785" alt="Screenshot 2024-09-26 at 8 50 01 AM" src="https://github.com/user-attachments/assets/147b553a-ffd3-4bef-b029-0be71b8a8ab0">

**Comment by mvoutov** [comment]
fixed with #121
