### ISSUE TITLE
Simplify download part of sidebar

### ISSUE THREAD

**Issue by andrewpbray** [gradebook-dev/gradebook-app#105]
Simplify download part of sidebar to read "Download files, then have two side-by-side buttons with download icons: "Grades" and "Policy File"

**Comment by mvoutov** [comment]
<img width="1170" alt="image" src="https://github.com/user-attachments/assets/78a5d204-936d-4370-9145-4cad3725d5e4">
@andrewpbray what do you think ?

**Comment by andrewpbray** [comment]
I think that's fantastic. What do you think?

**Comment by mvoutov** [comment]
1) <img width="1512" alt="image" src="https://github.com/user-attachments/assets/839ea2f5-ffbd-4019-9002-fa240ac55afe">
2) <img width="1171" alt="image" src="https://github.com/user-attachments/assets/24fd0201-b3a4-4b8f-bdf7-6c4ef10d4714">

**Comment by andrewpbray** [comment]
It feels like usually the icon is associated with the link - what would it look like for the only icons to be on the buttons?

**Comment by andrewpbray** [comment]
(oh, that's the first one!)

**Comment by mvoutov** [comment]
<img width="468" alt="image" src="https://github.com/user-attachments/assets/54d1eece-7f01-4717-aa12-72b22ac8bed9">

**Comment by andrewpbray** [comment]
Either either the icon above or the icon on the buttons works. The former once has the advantage of looking like the uploads. I'm not a fan of the triple icon.

**Comment by mvoutov** [comment]
<img width="526" alt="image" src="https://github.com/user-attachments/assets/08a32301-bac4-4ad4-b4f0-48223654056f">

I agree -- do not like the 3 icons.

**Comment by andrewpbray** [comment]
Btw, this is a great way to evaluate aesthetic things: put screenshots from local in the PR convo, then commit whatever is decided on.

**Comment by mvoutov** [comment]
Yes! 

I think I like this one best:
<img width="613" alt="image" src="https://github.com/user-attachments/assets/bbe74e56-318d-4500-9d31-238b4b3d8c7e">

**Comment by andrewpbray** [comment]
Great - lets do it!

**Comment by mvoutov** [comment]
I was trying to attach the PR to this issue but I could not.

**Comment by andrewpbray** [comment]
Ah, that's a good point. I normally do it through the **Development** menu item on the right sidebar here. Looks like kyou can only link to branches on this repo, not branches that are on forks of this repo. 

You can link the two in a different way using the issue number in the PR convo. I'll demonstrate that over there.

**Comment by mvoutov** [comment]
I think I did it -- let's see if it closes with the PR.

**Comment by andrewpbray** [comment]
Hmm, well it linked it (it's visible here in the convo and in the right sidebar) but it didn't close it... kinda surprising.

**Comment by mvoutov** [comment]
I guess I should've created a branch from the issue , then PR to that branch. next time.
