### ISSUE TITLE
Could not find function "tabitem"

### ISSUE THREAD

**Issue by ryanlovett** [gradebook-dev/gradebook-app#48]
When I try running the v30 branch in a container from within RStudio, I see the warning message below. A new window pops up with the heading "An error has occurred!" along with the same 'could not find function "tabitem"' message. I do have `shinydashboard` installed.

If I add `library(shinydashboard)` to the top of each of the `ui-components` files, the issue goes away.

```
> shiny::runApp('R')
Loading required package: shiny

Attaching package: ‘shiny’

The following objects are masked from ‘package:DT’:

    dataTableOutput, renderDataTable


Listening on http://127.0.0.1:5460
Warning: Error in tabItem: could not find function "tabItem"
  65: eval [ui-components/files.R#1]
  64: eval
  62: source
   1: shiny::runApp
```

**Comment by mvoutov** [comment]
@ryanlovett Ryan, thank you for pointing this out. Yes, we need to have `library(shinydashboard)` in the beginning of ui.R.
