### ISSUE TITLE
Add demo policy

### ISSUE THREAD

**Issue by mvoutov** [gradebook-dev/gradebook-app#77]
- [ ] Making demo policy to load in the app

**Comment by mvoutov** [comment]
Commented out this for now.

**Comment by mvoutov** [comment]
@andrewpbray @nikita-jaya @ZBallDiesel  : Are we adding demo policy at all ?

**Comment by andrewpbray** [comment]
I like the simpler state of the app for now, where we guide users to upload local files. Ok if I close this issue?

**Comment by mvoutov** [comment]
I agree!
