### ISSUE TITLE
Policy cards don't agree with downloaded policy file

### ISSUE THREAD

**Issue by andrewpbray** [gradebook-dev/gradebook-app#92]
**Describe the bug**
The cards shown for subcategories will show "trickle-down" behavior - lateness policies will get inherited from the parent category. When you download the policy file, however, that lateness policy will only appear on the parent policy.

**To Reproduce**
1. Create a category with two new subcategories as assignments.
2. Add a lateness policy to the parent category.
3. See the way the lateness policy is copied down into the subcategories.
4. Download the policy file and see that the lateness policy only shows up in the parent category.

**Expected behavior**
Ultimately: the displayed policy file in the app should reflect the structure of the actual policy file that is downloaded.

Specific to this issue, the lateness show not show up in the cards in subcategories unless it is explicitly added.

**Screenshots**

<img width="718" alt="Screenshot 2024-05-13 at 10 38 06 AM" src="https://github.com/gradebook-dev/gradebook-app/assets/1627362/be1fcfa3-0c74-4d8a-b2ca-be0b7d7a2921">

**Comment by mvoutov** [comment]
This issue must have been fixed -- currently lateness does not trickle down from parent (I.e. only parent has the lateness policy in it):
<img width="830" alt="image" src="https://github.com/user-attachments/assets/b46ed687-a56e-4fd3-a3f0-86e326d44e29">
